apiVersion: apps/v1
kind: Deployment
metadata:
  name: apachewebsite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apachewebsite
  template:
    metadata:
      labels:
        app: apachewebsite
    spec:
      containers:
      - name: apachewebsite
        image: <dockerhub-username>/apachewebsite:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: apachewebsite-service
spec:
  type: LoadBalancer
  selector:
    app: apachewebsite
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

